services:
  - type: web
    name: katha-naka-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python seeds.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONUNBUFFERED
        value: "1"
